### ISSUE TITLE
I get the Fiber but what's Stack?

### ISSUE THREAD

**Issue by abdulhannanali** [claudiopro/react-fiber-vs-stack-demo#2]
Hey React Fiber Seems super fast from the example. However, I am not very aware with the Stack, is it the name of the technology behind the previous version of react? Any pointers will be very appreciated. Thanks a lot that's a cool triangle example.

**Comment by claudiopro** [comment]
Hi @abdulhannanali, yes that's correct. Stack is a posthumous name given to the pre-existing implementation of React's reconciler. [Watch this recording](https://www.youtube.com/watch?v=crM1iRVGpGQ0) by Kent C. Dodds for further details. Thanks for stopping by and taking the time to comment!

**Comment by abdulhannanali** [comment]
Thanks a lot for answering the query @claudiopro Seems really exciting
